### ISSUE TITLE
Access to previous runs

### ISSUE THREAD

**Issue by mdi** [nature/webpagetest-mapper#7]
I have results from a few previous runs that I'd like to run through webpagetest-mapper. Is there a way to do this?

**Comment by philbooth** [comment]
Right now there isn't. But it would be straightforward to add an option that lets you do this.

What would you like to use as input, result ids or the actual result JSON? Or both? :)

**Comment by mdi** [comment]
Either/or. Whichever is easier.

**Comment by philbooth** [comment]
Hey @mdi, I've published this feature as version 0.1.0 on npm.

You can now specify a command-line option `-i <ids>` or `--resultIds <ids>`, where `<ids>` is a comma-separated list of WebPageTest result ids.

Because all the data with this option is coming directly from WebPageTest rather than our config, there are a couple of things you should be aware of:

* The name field for each result is copied from the label or, if there is no label, the id itself.
* The timestamps for these results are wrong, being the time they were fetched rather than the time they were recorded.
* The `home`/`away` setting that is used to differentiate results in the `html-comparison` mapper is forced to `home` in these cases.

Let me know if there are any problems. :)

**Comment by mdi** [comment]
This is great! Thanks!

**Comment by mdi** [comment]
I'm seeing one small error with run http://www.webpagetest.org/result/150505_60_C1B/

The error is: `TypeError: Cannot read property 'speedIndex' of undefined`

**Comment by philbooth** [comment]
Ah, apologies, will take a look tomorrow. Have raised #9 to cover it.
